api/urls.py
from django.contrib import admin
from django.urls import path
from . import views
app_name = "api"

urlpatterns = [
    # path('dashboard/',views.dashboard,name = "dashboard"),
    path('addstatic/',views.addStatic,name = "addstatic"),
    path('',views.addStatic,name = "addstatic"),
    path('addvcard/',views.addVcard,name = "addvcard"),
    path('adddynamic/',views.addDynamic,name = "adddynamic"),
    path('apistatic/',views.apistatic,name = "apistatic"),
    path('apidynamic/',views.apidynamic,name = "apidynamic"),
    path('apivcard/',views.apivcard,name = "apivcard"),   
]

mobstac/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static


from api import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("api.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.


class staticQR(models.Model):
    auth_token = '82f46feaee08dd185dac1adcef06f8b5b381c75f'
    name = models.CharField(max_length = 50,verbose_name = "Name")
    qr_type = 1
    organization = 5419
    url = models.CharField(max_length = 400,verbose_name = "Url")
    qr_url = None
    qr_id = None
    def __str__(self):
        return self.name

    # class Meta:
    #     ordering = ['-created_date']

class dynamicQR(models.Model):
    auth_token = '82f46feaee08dd185dac1adcef06f8b5b381c75f'
    name = models.CharField(max_length = 50,verbose_name = "Name")
    qr_type = 2
    organization = 5419
    content_type = 1
    custom_url = models.CharField(max_length = 400,verbose_name = "Url")
    qr_url = None
    qr_id = None
    def __str__(self):
        return self.name

    # class Meta:
    #     ordering = ['-created_date']

class Vcard(models.Model):
    auth_token = '82f46feaee08dd185dac1adcef06f8b5b381c75f'
    name = models.CharField(max_length = 50,verbose_name = "Name of QR")
    qr_type = 2
    organization = 5419
    content_type = 7
    first_name= models.CharField(max_length = 50,verbose_name = "First Name")
    last_name = models.CharField(max_length = 50,verbose_name = "Last Name")
    user_image_url = models.CharField(max_length = 600,verbose_name = "User Image Url")
    phone_mobile = models.CharField(max_length = 15,verbose_name = "Mobile Number")
    email = models.EmailField(max_length = 100,verbose_name = "Email id")
    qr_url = None
    qr_id = None
    def __str__(self):
        return self.name

api/forms.py
from django import forms
from .models import staticQR,dynamicQR,Vcard
class StaticForm(forms.ModelForm):
    class Meta:
        model = staticQR
        fields = ["name","url"]
class DynamicForm(forms.ModelForm):
    class Meta:
        model = dynamicQR
        fields = ["name","custom_url"]

class VcardForm(forms.ModelForm) :
    class Meta:
        model = Vcard
        fields = ["name","first_name","last_name","user_image_url","phone_mobile","email"]

api/views.py
from django.shortcuts import render,HttpResponse,redirect,get_object_or_404,reverse
from .forms import StaticForm, DynamicForm,VcardForm
from .models import staticQR,dynamicQR,Vcard
import requests
import json
def apistatic(request):
    s = staticQR.objects.all()
    S = s[len(s)-1]

    url = "https://api.beaconstac.com/api/2.0/qrcodes/"
    p = {
        "name": S.name,
        "qr_type": S.qr_type,
        "organization": S.organization,
        "attributes": {
            "color": "#000000",
            "margin": 25
        },
        "fields_data": {
            "qr_type": 1,
            "url": S.url
        }
    }
    payload = json.dumps(p)
    headers = {
    'Authorization': 'Token '+ S.auth_token,
    'Content-Type': 'application/json'
    }

    response = requests.request("POST", url, headers=headers, data = payload)
    result = response.json()
    qr_id = result['id']
    params = (
    ('canvas_type', 'png'),
    )
    headers2 = {
    'Authorization': 'Token '+ S.auth_token
    }
    response2 = requests.get('https://api.beaconstac.com/api/2.0/qrcodes/'+str(qr_id)+'/download/', params=params,headers=headers2)
    image_data = response2.json()
    name = image_data['name']
    url = image_data['urls']['png']
    S.qr_id = qr_id
    S.qr_url = url
    return render(request,"staticqr.html",{'name' : name,
                                            'url' : url})



def apidynamic(request):
    d = dynamicQR.objects.all()
    D = d[len(d)-1]

    url = "https://api.beaconstac.com/api/2.0/qrcodes/"
    p = {
        "name": D.name,
        "qr_type": D.qr_type,
        "organization": D.organization,
        "attributes": {
            "color": "#000000",
            "margin": 25
        },
        "campaign": {
            "custom_url": D.custom_url,
            "content_type": D.content_type,
        }
    }
    payload = json.dumps(p)
    headers = {
    'Authorization': 'Token '+ D.auth_token,
    'Content-Type': 'application/json'
    }

    response = requests.request("POST", url, headers=headers, data = payload)
    result = response.json()
    qr_id = result['id']
    params = (
    ('canvas_type', 'png'),
    )
    headers2 = {
    'Authorization': 'Token '+ D.auth_token
    }
    response2 = requests.get('https://api.beaconstac.com/api/2.0/qrcodes/'+str(qr_id)+'/download/', params=params,headers=headers2)
    image_data = response2.json()
    name = image_data['name']
    url = image_data['urls']['png']
    D.qr_id = qr_id
    D.qr_url = url
    return render(request,"dynamicqr.html",{'name' : name,
                                            'url' : url})



def apivcard(request):
    v = Vcard.objects.all()
    V = v[len(v)-1]

    url = "https://api.beaconstac.com/api/2.0/qrcodes/"
    p = {
        "name": V.name,
        "qr_type": V.qr_type,
        "organization": V.organization,
        "attributes": {
            "color": "#fb6e6e",
            "margin": 25
        },
        "campaign": {
            "content_type": V.content_type,
            "vcard_plus": {
                "first_name": V.first_name,
                "last_name": V.last_name,
                "user_image_url": V.user_image_url,
                "phone": {
                    "mobile": V.phone_mobile
                },
                "email": V.email,
                "customizations": {
                    "background_color": "#2594FF",
                    "user_info_color": "#FFFFFF"
                }
            }
        }
    }
    payload = json.dumps(p)
    headers = {
    'Authorization': 'Token '+ V.auth_token,
    'Content-Type': 'application/json'
    }

    response = requests.request("POST", url, headers=headers, data = payload)
    result = response.json()
    qr_id = result['id']
    params = (
    ('canvas_type', 'png'),
    )
    headers2 = {
    'Authorization': 'Token '+ V.auth_token
    }
    response2 = requests.get('https://api.beaconstac.com/api/2.0/qrcodes/'+str(qr_id)+'/download/', params=params,headers=headers2)
    image_data = response2.json()
    name = image_data['name']
    url = image_data['urls']['png']
    V.qr_id = qr_id
    V.qr_url = url
    return render(request,"vcardqr.html",{'name' : name,
                                            'url' : url})


def addStatic(request):
    form = StaticForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        staticqr = form.save(commit=False)
        
        staticqr.save()

        return redirect("api:apistatic")
    return render(request,"addstatic.html",{"form":form})


def addDynamic(request):
    form = DynamicForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        dynamicqr = form.save(commit=False)
        dynamicqr.save()

        return redirect("api:apidynamic")
    return render(request,"adddynamic.html",{"form":form})

def addVcard(request):
    form = VcardForm(request.POST or None,request.FILES or None)

    if form.is_valid():
        vcardqr = form.save(commit=False)
        vcardqr.save()

        return redirect("api:apivcard")
    return render(request,"addvcard.html",{"form":form})

templates/adddynamic.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create DynamicQR</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Create QR</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/addstatic.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create StaticQR</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Create QR</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/addvcard.html
{% extends "layout.html" %}

{% block body %}
{% load crispy_forms_tags %}

<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>Create VcardQR</h3>
        <hr>
        <form method = "post" enctype="multipart/form-data">
            {% csrf_token %}
            {{form.media}}
            {{form|crispy}}
            <br>
            <button type = "submit" class = "btn btn-danger">Create QR</button>
        </form>
    </div>
  </div>


{% endblock body %}

templates/dynamicqr.html
{% extends "layout.html" %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>DynamicQR</h3>
        <hr>
        {% if detail %}
            {{detail}}
        {% else %}
            <h4><a href="{{url}}">{{name}} (download)</a></h4>
            <img src="{{url}}"style="max-width:250px;height:auto; ">
            
        {% endif %}
    </div>
  </div>

{% endblock body %}

templates/includes/navbar.html
<header>
	<div class="top-nav" style="background:inherit">
		<div class="container-fluid">
			<nav class="navbar navbar-expand-lg navbar-light">
				<a class="navbar-brand text-uppercase" href="{% url 'api:addstatic'  %}">QR</a>
				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
				</button>
				<div class="collapse navbar-collapse justify-content-center pr-md-4" id="navbarSupportedContent">
					<ul class="navbar-nav ml-auto">
						<li class="nav-item">
							<a class="nav-link active" href="{% url 'api:addstatic'  %}">StaticQR</a>
							
						</li>
						<li class="nav-item">
							<a class="nav-link active" href="{% url 'api:adddynamic'  %}">DynamicQR</a>
							
						</li>
						<li class="nav-item">
							<a class="nav-link active" href="{% url 'api:addvcard'  %}">Vcard QR</a>
							
						</li>
					</ul>
				</div>
			</nav>
		</div>
	</div>
</header>
								
								

templates/layout.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    <head>
        <title>mobstac App</title>
        <link rel="shortcut icon" type="image/png" href="{{MEDIA_URL}}favicon.png">
            <!-- Meta tag Keywords -->
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <meta charset="utf-8">
            <meta name="keywords" content="mobstac APP by ANURAG" />
            <script type="application/x-javascript">
                addEventListener("load", function () {
                    setTimeout(hideURLbar, 0);
                }, false);
                function hideURLbar() {
                    window.scrollTo(0, 1);
                }
            </script>
            <!--// Meta tag Keywords -->
        
            <!-- css files -->
            <link rel="stylesheet" href="{% static 'assets/css/bootstrap.css' %}"> <!-- Bootstrap-Core-CSS -->
            <link rel="stylesheet" href="{% static 'assets/css/style.css' %}" type="text/css" media="all" /> <!-- Style-CSS --> 
            <link rel="stylesheet" href="{% static 'assets/css/fontawesome-all.css' %}"> <!-- Font-Awesome-Icons-CSS -->
            <!-- //css files -->
            <link href="{% static 'assets/css/easy-responsive-tabs.css' %}" rel='stylesheet' type='text/css'/>
            <link rel="stylesheet" href="{% static 'assets/css/jquery-ui.css' %}" /><!-- Calendar -->
            <!-- testimonials css -->
            <link rel="stylesheet" href="{% static 'assets/css/flexslider.css' %}" type="text/css" media="screen" property="" /><!-- flexslider css -->
            <!-- //testimonials css -->
            <style>
            .navbar-custom {
                background-color: #006064;
            }
            body {
                color: #004d40;
            }
            .icon-link {
                text-decoration: none;
                color: inherit;
            }
            p {
                color: #004d40;
            }
            .bcx {
                width : 400px;
                height: 260px;
            }
            .searchbar {
                width: 86%;
                padding: 0.375rem 0.75rem;
                font-size: 1rem;
                line-height: 1.5;
                color: #495057;
                background-color: #fff;
                background-clip: padding-box;
                border: 1px solid #ced4da;
                border-radius: 0.25rem;
                transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
            }</style>
            <!-- web-fonts -->
            <link href="//fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i,800,800i" rel="stylesheet">
            <link href="//fonts.googleapis.com/css?family=Roboto+Slab:100,300,400,700&amp;subset=cyrillic,cyrillic-ext,greek,greek-ext,latin-ext,vietnamese" rel="stylesheet">
            <!-- //web-fonts -->
</head>
    <body >  
        {% include "includes/navbar.html" %}
        <br>
        <br>
        <br>
        <br>
        <br>
        {% block body %} 
        {% endblock body %}
    </body>
    <!-- js-scripts -->		

	<!-- js -->
	<script type="text/javascript" src="{% static 'assets/js/jquery-2.1.4.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/js/bootstrap.js' %}"></script> <!-- Necessary-JavaScript-File-For-Bootstrap --> 
	<!-- //js -->	
	
	<!-- Banner Responsive slider -->
	<script src="{% static 'assets/js/responsiveslides.min.js' %}"></script>
	<script>
		// You can also use "$(window).load(function() {"
		$(function () {
			// Slideshow 4
			$("#slider4").responsiveSlides({
				auto: true,
				pager: false,
				nav: true,
				speed: 500,
				namespace: "callbacks",
				before: function () {
					$('.events').append("<li>before event fired.</li>");
				},
				after: function () {
					$('.events').append("<li>after event fired.</li>");
				}
			});

		});
	</script>
	<!-- // Banner Responsive slider -->
	<!-- script for responsive tabs -->						
    <script src="{% static 'assets/js/easy-responsive-tabs.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('#horizontalTab').easyResponsiveTabs({
                type: 'default', //Types: default, vertical, accordion           
                width: 'auto', //auto or any width like 600px
                fit: true,   // 100% fit in a container
                closed: 'accordion', // Start closed if in accordion view
                activate: function(event) { // Callback function if tab is switched
                    var $tab = $(this);
                    var $info = $('#tabInfo');
                    var $name = $('span', $info);
                    $name.text($tab.text());
                    $info.show();
                }
            });
            $('#verticalTab').easyResponsiveTabs({
            type: 'vertical',
            width: 'auto',
            fit: true
            });
        });
    </script>
    <!--script for responsive tabs -->
    <!-- Calendar -->
    <script src="{% static 'assets/js/jquery-ui.js' %}"></script>
        <script>
            $(function() {
                $( "#datepicker,#datepicker1,#datepicker2,#datepicker3" ).datepicker();
            });
        </script>
    <!-- //Calendar -->
    <!-- stats -->
	<script src="{% static 'assets/js/jquery.waypoints.min.js' %}"></script>
	<script src="{% static 'assets/js/jquery.countup.js' %}"></script>
	<script>
		$('.counter').countUp();
	</script>
	<!-- //stats -->
	<!-- flexSlider --><!-- for testimonials -->
	<script defer src="{% static 'assets/js/jquery.flexslider.js' %}"></script>
	<script type="text/javascript">
		$(window).load(function(){
		  $('.flexslider').flexslider({
			animation: "slide",
			start: function(slider){
			  $('body').removeClass('loading');
			}
		  });
		});
	</script>
	<!-- //flexSlider --><!-- for testimonials -->

	<!-- start-smoth-scrolling -->
	<script src="{% static 'assets/js/SmoothScroll.min.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/js/move-top.js' %}"></script>
	<script type="text/javascript" src="{% static 'assets/js/easing.js' %}"></script>
	<script type="text/javascript">
		jQuery(document).ready(function($) {
			$(".scroll").click(function(event){		
				event.preventDefault();
				$('html,body').animate({scrollTop:$(this.hash).offset().top},1000);
			});
		});
	</script>
	<!-- here stars scroslling icon -->
	<script type="text/javascript">
		$(document).ready(function() {
			/*
				var defaults = {
				containerID: 'toTop', // fading element id
				containerHoverID: 'toTopHover', // fading element hover id
				scrollSpeed: 1200,
				easingType: 'linear' 
				};
			*/
								
			$().UItoTop({ easingType: 'easeOutQuart' });
								
			});
	</script>
	<!-- //here ends scrolling icon -->
	<!-- start-smoth-scrolling -->
	
<!-- //js-scripts -->

</html>

templates/staticqr.html
{% extends "layout.html" %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>StaticQR</h3>
        <hr>
        {% if detail %}
            {{detail}}
        {% else %}
            <h4><a href="{{url}}">{{name}} (download)</a></h4>
            <img src="{{url}}"style="max-width:250px;height:auto; ">
        {% endif %}
    </div>
  </div>
{% endblock body %}

templates/vcardqr.html
{% extends "layout.html" %}

{% block body %}


<div class="row">
    <div class="col-md-6 offset-md-3">
        <h3>VcardQR</h3>
        <hr>
        {% if detail %}
            {{detail}}
        {% else %}
            <h4><a href="{{url}}">{{name}} (download)</a></h4>
            <img src="{{url}}"style="max-width:250px;height:auto; ">
            
        {% endif %}
    </div>
  </div>

{% endblock body %}